CREATE TABLE IF NOT EXISTS roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO roles (name) VALUES ('SUPER_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('DOCTOR') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('STAFF') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('PATIENT') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ACCOUNTANT') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('LAB_TECH') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('PHARMACY') ON CONFLICT DO NOTHING;
