CREATE TABLE IF NOT EXISTS roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO roles (name) VALUES ('ROLE_SUPER_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_DOCTOR') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_STAFF') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_PATIENT') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_ACCOUNTANT') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_LAB_TECH') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_PHARMACY') ON CONFLICT DO NOTHING;
